server:
  port: 9000
spring:
  application:
    name: coupon-gateway

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/

zuul:
  prefix: /imooc
  routes:
    # 优惠券模版微服务路由配置定义
    template:
      path: /coupon-template/**
      serviceId: eureka-client-coupon-template
      strip-prefix: false
    # 优惠券结算微服务路由配置定义
    settlement:
      path: /coupon-settlement/**
      serviceId: eureka-client-coupon-settlement
      strip-prefix: false
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000

ribbon:
  ConnectTimeout: 15000
  ReadTimeout: 15000
